export const PRICING_TABLE = [
  {
    key: "6mm",
    thickness: "6mm",
    sub: "Sân vườn, bao song, lối đi nhẹ",
    p200_500: 85000,
    p500_1000: 77000,
    pAbove1000: 68000,
    tags: ["Sân vườn", "Bao song", "Hành lang"],
    isPopular: false,
    basePrice: 68000,
  },
  {
    key: "8mm",
    thickness: "8mm",
    sub: "Nhà xưởng, kho bãi thông thường",
    p200_500: 93000,
    p500_1000: 84000,
    pAbove1000: 78000,
    tags: ["Nhà xưởng", "Kho hàng", "Garage"],
    isPopular: false,
    basePrice: 78000,
  },
  {
    key: "10mm",
    thickness: "10mm",
    sub: "Phổ biến nhất — phân xưởng, cầu cảng",
    p200_500: 95000,
    p500_1000: 90000,
    pAbove1000: 85000,
    tags: ["Phân xưởng", "Sân bay", "Bãi đỗ xe"],
    isPopular: true,
    basePrice: 85000,
  },
  {
    key: "12mm",
    thickness: "12mm",
    sub: "Chịu tải nặng, máy móc trọng lượng lớn",
    p200_500: 105000,
    p500_1000: 100000,
    pAbove1000: 95000,
    tags: ["Kho cảng", "Nông thôn", "Đường xe tải"],
    isPopular: false,
    basePrice: 95000,
  },
  {
    key: "15mm",
    thickness: "15mm",
    sub: "Cực kỳ bền — tải trọng lớn & độ ẩm cao",
    p200_500: 130000,
    p500_1000: 124000,
    pAbove1000: 116000,
    tags: ["Cảng container", "Khu hóa chất", "Công trình đặc biệt"],
    isPopular: false,
    basePrice: 116000,
  },
];

export const ADVANTAGES = [
  {
    icon: "🧱",
    title: "Độ bền 8–10 năm",
    desc: "Bê tông cuộn sản xuất theo tiêu chuẩn công nghiệp, chịu tải nén cao, không nứt vỡ theo thời gian.",
  },
  {
    icon: "💧",
    title: "Chống thấm tuyệt đối",
    desc: "Bề mặt xử lý đặc biệt, chống thấm nước và dầu mỡ, dễ vệ sinh bằng áp lực nước.",
  },
  {
    icon: "❄️",
    title: "Cách âm, cách nhiệt",
    desc: "Lớp sợi thủy tinh giúp giảm tiếng ồn và cách nhiệt hiệu quả cho không gian phía dưới.",
  },
  {
    icon: "⚡",
    title: "Lắp đặt nhanh",
    desc: "Không cần trộn vữa, không chờ khô. Rải là hoàn thành — tiết kiệm 80% thời gian thi công.",
  },
  {
    icon: "👷",
    title: "Hỗ trợ thi công",
    desc: "Công trình trên 5.000m² được đội ngũ kỹ thuật hỗ trợ tại công trường trực tiếp từ chúng tôi.",
  },
  {
    icon: "🚚",
    title: "Giao hàng toàn quốc",
    desc: "Hệ thống vận chuyển chuyên dụng, đảm bảo sản phẩm đến tay khách hàng nguyên vẹn.",
  },
];
